select trunc(sysdate,'Month') "First day of vurrent month" from dual;

select trunc(LAST_DAY(sysdate)) "Last day of cuureent month" from dual;

select current_date from dual;

alter session set time_zone ='-8:0';
alter session set nls_date_format='DD-MM-YYYY HH24:MI:SS';
SELECT SESSIONTIMEZONE,CURRENT_DATE FROM DUAL;
ALTER SESSION SET TIME_ZONE='-9:0';
SELECT SESSIONTIMEZONE,CURRENT_DATE FROM DUAL;

SELECT ROUND(TRUNC(laST_DAY(SYSDATE))-SYSDATE) FROM DUAL;

select TRUNC(SYSDATE,'YEAR') FROM DUAL;
SELECT ADD_MONTHS (TRUNC(SYSDATE,'YEAR'),12)-1 FROM DUAL;

SELECT CAST(TO_CHAR(LAST_DAY(SYSDATE),'DD') AS INT) NO_OF_DAYS FROM DUAL;

SELECT ROUND((monthS_BETWEEN('01-MAY-2024','01-DEC-2023')*30),0) NO_OF_DAYS FROM DUAL;

SELECT TO_DATE('jan2021','MONYYYY') FROM DUAL;

SELECT LAST_DAY(TO_DATE('JAN2021','MONYYYY')) FROM DUAL;

SELECT  LAST_DAY(TO_DATE('JAN2021','MONYYYY'))-TO_DATE('jan2021','MONYYYY')+1 AS NO_OF_DAYS FROM DUAL;

WITH D AS (SELECT(TO_DATE('jan2021','MONYYYY')) S_DATE,
( LAST_DAY(TO_DATE('JAN2021','MONYYYY'))) L_DATE,
(LAST_DAY(TO_DATE('JAN2021','MONYYYY'))-TO_DATE('jan2021','MONYYYY')+1) NO_OF_DAYS FROM DUAL
)
SELECT S_DATE,LEVEL-1,S_DATE+LEVEL-1 CAL_DATE
FROM D CONNECT BY LEVEL<=NO_OF_DAYS;

