SELECT INTERVAL '01-06' YEAR TO MONTH FROM DUAL;    
SELECT INTERVAL '-01-06' YEAR TO MONTH FROM DUAL;
SELECT INTERVAL '150-06' YEAR(3) TO MONTH FROM DUAL;

SELECT INTERVAL '21' YEAR FROM DUAL;
SELECT INTERVAL '06' MONTH FROM DUAL;
SELECT INTERVAL '16' MONTH FROM DUAL;
SELECT INTERVAL '-16' MONTH FROM DUAL;

CREATE TABLE T(DURATION_OF_STAY INTERVAL YEAR(4) TO MONTH);
DESC T;
INSERT INTO T VALUES (
(INTERVAL '01-06' YEAR TO MONTH));   
INSERT INTO T VALUES(INTERVAL '-01-06' YEAR TO MONTH);
INSERT INTO T VALUES(INTERVAL '150-06' YEAR(3) TO MONTH);
INSERT INTO T VALUES(INTERVAL '21' YEAR);
INSERT INTO T VALUES(INTERVAL '06' MONTH);
INSERT INTO T VALUES(INTERVAL '16' MONTH);
INSERT INTO T VALUES(INTERVAL '-16' MONTH);
INSERT INTO T VALUES(INTERVAL '200-11' YEAR(3) TO MONTH);

DROP TABLE T;
SELECT * FROM T;

select interval '1-2' year to month from dual;

select interval '1-2' year to month +interval '1-11' year to month from dual;

select interval '1-2' year to month -interval '1-11' year to month from dual;

select interval '1-2' year to month *2 from dual;

select interval '1-2' year to month /2 from dual;

